### PR TITLE
Josh

### PR DESCRIPTION
**Pull request by Joshua-Frost**
Login screen now working
Firebase auth modified
Auth context added
LoginView, RegisterView, ResetPasswordView moved to auth folder

### CODE REVIEW

**Review by FranTheCaveman — CHANGES_REQUESTED** [review]
# Looks good!
Wow that's a lot of changes! 

Navigation seems to work after registering a new account and logging in with correct details. Invalid details in register works too. However, inputting invalid values in the login screen results in an infinite loading screen.

Should we continue to merge & fix later, or fix the infinite loading first?

**Comment by Joshua-Frost** [comment]
Nice catch, I think I should fix it first then I'll resubmit the pull request

**Comment by Joshua-Frost** [comment]
### All fixed!
If you agree, feel free to merge 👍

**Comment by itsLucas-h** [comment]
Nice work Josh

**Pull request merged**
